# Advertising Dataset

#### Load and preprocess the Advertising.csv dataset.
#### Build and train a Linear Regression model to predict the target variable.

### Requirements:
- Load the dataset.
- Perform required preprocessing.
- Split the data into training and testing sets.
- Train a Linear Regression model.
- Evaluate the model using:
- Mean Absolute Error (MAE)
- R² Score
- Create a Predictive Function that takes new input values and returns the prediction.
- Test the predictive function with at least one new input.

In [2]:
import pandas as pd
data = pd.read_csv("Advertising.csv")

In [3]:
data.head()

   ID     TV  Radio  Newspaper  Sales
0   1  230.1   37.8       69.2   22.1
1   2   44.5   39.3       45.1   10.4
2   3   17.2   45.9       69.3    9.3
3   4  151.5   41.3       58.5   18.5
4   5  180.8   10.8       58.4   12.9

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         200 non-null    int64
 1   TV         200 non-null    float64
 2   Radio      200 non-null    float64
 3   Newspaper  200 non-null    float64
 4   Sales      200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB

In [5]:
data.isnull().sum()

ID           0
TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [38]:
X = data[["TV", "Radio", "Newspaper"]]
y = data["Sales"]

In [55]:
X.isnull().sum()

TV           0
Radio        0
Newspaper    0
dtype: int64

In [40]:
y.shape

(200,)

In [41]:
X.head()

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [42]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2 , random_state=42)

In [45]:
from sklearn.linear_model import LinearRegression

In [46]:
model = LinearRegression()

In [47]:
model.fit(X_train, y_train)

LinearRegression()

In [69]:
model.coef_

array([0.04472952, 0.18919505, 0.00276111])

In [70]:
model.intercept_

np.float64(2.979067338122629)

In [48]:
y_pred = model.predict(X_test)

In [49]:
y_test.head(10).values

array([16.9, 22.4, 21.4,  7.3, 24.7, 12.6, 22.3,  8.4, 11.5, 14.9])

In [56]:
from sklearn.metrics import mean_absolute_error, r2_score

In [59]:
mean_absolute_error(y_test, y_pred)

1.4607567168117603

In [51]:
r2_score(y_test, y_pred)

0.899438024100912

In [75]:
def predict_sales():

    tv = float(input("Enter TV advertising"))
    radio = float(input("Enter Radio advertising"))
    newspaper = float(input("Enter Newspaper advertising"))

    # Save the data in new dataframe nad predict this
    new_data = pd.DataFrame({
        "TV": [tv],
        "Radio": [radio],
        "Newspaper": [newspaper]
    })

    prediction = model.predict(new_data)

    print(prediction)

In [76]:
predict_sales()

Enter TV advertising 129
Enter Radio advertising 21
Enter Newspaper advertising 21

[12.78025463]