# Make a Housing Prices Machine Learning Pipline
```
Load and preprocess the dataset, build an ML Pipeline, and decide whether Linear Regression or Polynomial Regression performs better. Evaluate the model using MAE and R² Score and create a predictive function for new inputs.
```

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [4]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [5]:
df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

# Data Splited

In [6]:
X = df.drop("price", axis=1)
y = df[["price"]]

In [7]:
X,y

(     area  bedrooms  bathrooms  stories mainroad guestroom basement  \
 0    7420         4          2        3      yes        no       no
 1    8960         4          4        4      yes        no       no
 2    9960         3          2        2      yes        no      yes
 3    7500         4          2        2      yes        no      yes
 4    7420         4          1        2      yes       yes      yes
 ..    ...       ...        ...      ...      ...       ...      ...
 540  3000         2          1        1      yes        no      yes
 541  2400         3          1        1       no        no       no
 542  3620         2          1        1      yes        no       no
 543  2910         3          1        1       no        no       no
 544  3850         3          1        2      yes        no       no

     hotwaterheating airconditioning  parking prefarea furnishingstatus
 0                no             yes        2      yes        furnished
 1                no             yes        3       no        furnished
 2                no              no        2      yes   semi-furnished
 3                no             yes        3      yes        furnished
 4                no             yes        2       no        furnished
 ..              ...             ...      ...      ...              ...
 540              no              no        2       no      unfurnished
 541              no              no        0       no   semi-furnished
 542              no              no        0       no      unfurnished
 543              no              no        0       no        furnished
 544              no              no        0       no      unfurnished

 [545 rows x 12 columns],
         price
 0    13300000
 1    12250000
 2    12250000
 3    12215000
 4    11410000
 ..        ...
 540   1820000
 541   1767150
 542   1750000
 543   1750000
 544   1750000

 [545 rows x 1 columns])

# Data Normalization

In [8]:
num_cols = X.select_dtypes(include="number")
cat_cols = X.select_dtypes(include="object")

In [9]:
num_cols

     area  bedrooms  bathrooms  stories  parking
0    7420         4          2        3        2
1    8960         4          4        4        3
2    9960         3          2        2        2
3    7500         4          2        2        3
4    7420         4          1        2        2
..    ...       ...        ...      ...      ...
540  3000         2          1        1        2
541  2400         3          1        1        0
542  3620         2          1        1        0
543  2910         3          1        1        0
544  3850         3          1        2        0

[545 rows x 5 columns]

In [10]:
cat_cols

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
0,yes,no,no,no,yes,yes,furnished
1,yes,no,no,no,yes,no,furnished
2,yes,no,yes,no,no,yes,semi-furnished
3,yes,no,yes,no,yes,yes,furnished
4,yes,yes,yes,no,yes,no,furnished
...,...,...,...,...,...,...,...
540,yes,no,yes,no,no,no,unfurnished
541,no,no,no,no,no,no,semi-furnished
542,yes,no,no,no,no,no,unfurnished
543,no,no,no,no,no,no,furnished
544,yes,no,no,no,no,no,unfurnished

# Data Ready for Training & Testing

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing Pipline

In [12]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline([
     ("imputer", SimpleImputer(strategy="most_frequent")),
     ("encoder", OneHotEncoder(handle_unknown="ignore",sparse_output=False))
])

# Column Transformer

In [13]:
preprocessor = ColumnTransformer([
    ("num", num_pipeline, make_column_selector(dtype_include=np.number)),
    ("cat", cat_pipeline, make_column_selector(dtype_include=object))
])

In [14]:
pipline_model = Pipeline([
    ("preprocessing" , preprocessor),
    ("model", LinearRegression())
])

In [15]:
polynomial_pipeline_model = Pipeline([
    ("preprocessing", preprocessor),
    ("poly", PolynomialFeatures(degree=2, include_bias=False)),
    ("model", LinearRegression())
])

In [16]:
polynomial_pipeline_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001DD57CA2900>),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001DD57BFBB10>)])),
                ('poly', PolynomialFeatures(include_bias=False)),
                ('model', LinearRegression())])

In [17]:
pipline_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001DD57CA2900>),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x000001DD57BFBB10>)])),
                ('model', LinearRegression())])

In [18]:
y_pred = pipline_model.predict(X_test)

In [19]:
y_pred_poly = polynomial_pipeline_model.predict(X_test)

# Model Evalution

In [20]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_absolute_error(y_test, y_pred))

In [21]:
mae_poly = mean_absolute_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

In [22]:
rmse

np.float64(984.9078149350652)

In [23]:
r2

0.6529242642153174

In [24]:
mae

970043.4039201646

In [25]:
mae_poly

1035032.9057097163

In [26]:
r2_poly

0.6236915318354186

In [27]:
def predict_house():
    area = float(input("Enter area: "))
    bedrooms = int(input("Enter bedrooms: "))
    bathrooms = int(input("Enter bathrooms: "))
    stories = int(input("Enter stories: "))
    mainroad = input("Mainroad (yes/no): ")
    guestroom = input("Guestroom (yes/no): ")
    basement = input("Basement (yes/no): ")
    hotwaterheating = input("Hot water heating (yes/no): ")
    airconditioning = input("Air conditioning (yes/no): ")
    parking = int(input("Enter parking spaces: "))
    prefarea = input("Preferred area (yes/no): ")
    furnishingstatus = input("Furnishing status (furnished/semi-furnished/unfurnished): ")

    new_data = pd.DataFrame({
        "area": [area],
        "bedrooms": [bedrooms],
        "bathrooms": [bathrooms],
        "stories": [stories],
        "mainroad": [mainroad],
        "guestroom": [guestroom],
        "basement": [basement],
        "hotwaterheating": [hotwaterheating],
        "airconditioning": [airconditioning],
        "parking": [parking],
        "prefarea": [prefarea],
        "furnishingstatus": [furnishingstatus]
    })

    prediction = pipline_model.predict(new_data)

    print("Predciton House Price",prediction[0])

In [30]:
predict_house()

Enter area:  12000
Enter bedrooms:  13
Enter bathrooms:  7
Enter stories:  3
Mainroad (yes/no):  yes
Guestroom (yes/no):  yes
Basement (yes/no):  yes
Hot water heating (yes/no):  yes
Air conditioning (yes/no):  yes
Enter parking spaces:  5
Preferred area (yes/no):  yes
Furnishing status (furnished/semi-furnished/unfurnished):  unfurnished

Predciton House Price [16779637.27269653]

In [29]:
print("Linear Regression MAE:", mae)
print("Linear Regression R²:", r2)
print("")
print("Polynomial Regression MAE:", mae_poly)
print("Polynomial Regression R²:", r2_poly)

Linear Regression MAE: 970043.4039201646
Linear Regression R²: 0.6529242642153174

Polynomial Regression MAE: 1035032.9057097163
Polynomial Regression R²: 0.6236915318354186